swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /prediction:
    get:
      operationId: "prediction.read"
      tags:
        - "SmartFailurePrediction"
      summary: "The HDD failure prediction by S.M.A.R.T data"
      description: "Read prediction records"
      responses:
        200:
          description: "Successful read prediction records"
          schema:
            type: "array"
            items:
              properties:
                timestamp:
                  type: "string"
                model:
                  type: 'string'
                serial_number:
                  type: "string"
                capacity_bytes:
                  type: "int"
                failure:
                  type: "int"
                prediction:
                  type: "int"
